import { mkdir, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  generatedRoot,
  loadTokenModel,
  cssVariableName,
  formatCssValue,
  resolveToken,
  sourceFiles,
  sourceHash,
  validateContrast,
  validateTokenModel,
} from './model.mjs';

const hashSource = (value) => createHash('sha256').update(value).digest('hex');

const resolvedValues = (model, themeName) => {
  const values = {};
  for (const [tokenPath, token] of model.semantic) {
    const resolved = resolveToken(model, tokenPath, themeName);
    values[tokenPath] = {
      value: resolved.value,
      type: resolved.type ?? token.type,
      cssVariable: cssVariableName(tokenPath),
    };
  }
  return values;
};

const flatValues = (model, themeName) => {
  const values = {};
  for (const [tokenPath, token] of model.semantic) {
    const resolved = resolveToken(model, tokenPath, themeName);
    values[cssVariableName(tokenPath)] = formatCssValue(
      resolved.value,
      resolved.type ?? token.type,
    );
  }
  return values;
};

const cssBlock = (selector, values) => {
  const lines = Object.entries(values).map(([variable, value]) => `  ${variable}: ${value};`);
  return `${selector} {\n${lines.join('\n')}\n}`;
};

const generateCss = (model) => {
  const blocks = [
    ':root {\n  color-scheme: dark;\n}',
    cssBlock(':root', flatValues(model, 'dark')),
    '@media (prefers-reduced-motion: reduce) {\n  :root {\n    --dui-motion-duration-feedback: 0ms;\n    --dui-motion-duration-standard: 0ms;\n    --dui-motion-duration-overlay: 0ms;\n  }\n}',
  ];
  return `${blocks.join('\n\n')}\n`;
};

const generateTokensTs = (model) => {
  const variables = Object.fromEntries(
    [...model.semantic.keys()].map((tokenPath) => [tokenPath, cssVariableName(tokenPath)]),
  );
  const values = flatValues(model, 'dark');
  return `// Generated by tooling/token-build/build.mjs. Do not edit.\nexport const semanticTokens = ${JSON.stringify(variables, null, 2)} as const;\n\nexport const tokenValues = ${JSON.stringify(values, null, 2)} as const;\n\nexport type SemanticTokenName = keyof typeof semanticTokens;\n\nexport const cssVariable = (name: SemanticTokenName): (typeof semanticTokens)[SemanticTokenName] => semanticTokens[name];\n`;
};

const generateTokensJs = (model) => {
  const variables = Object.fromEntries(
    [...model.semantic.keys()].map((tokenPath) => [tokenPath, cssVariableName(tokenPath)]),
  );
  const values = flatValues(model, 'dark');
  return `// Generated by tooling/token-build/build.mjs. Do not edit.\nexport const semanticTokens = ${JSON.stringify(variables, null, 2)};\n\nexport const tokenValues = ${JSON.stringify(values, null, 2)};\n\nexport const cssVariable = (name) => semanticTokens[name];\n`;
};

const generateDts = (model) => {
  const variableKeys = [...model.semantic.keys()]
    .map(
      (tokenPath) =>
        `  readonly ${JSON.stringify(tokenPath)}: ${JSON.stringify(cssVariableName(tokenPath))};`,
    )
    .join('\n');
  return `// Generated by tooling/token-build/build.mjs. Do not edit.\nexport declare const semanticTokens: {\n${variableKeys}\n};\nexport declare const tokenValues: Readonly<Record<string, string>>;\nexport type SemanticTokenName = keyof typeof semanticTokens;\nexport declare const cssVariable: (name: SemanticTokenName) => (typeof semanticTokens)[SemanticTokenName];\n`;
};

const generateManifest = (model) => {
  const reference = [...model.reference.values()].map(
    ({ path: tokenPath, type, value, description }) => ({
      path: tokenPath,
      type,
      value,
      description,
    }),
  );
  const semantic = [...model.semantic.values()].map(
    ({ path: tokenPath, type, value, description }) => ({
      path: tokenPath,
      type,
      value,
      description,
      cssVariable: cssVariableName(tokenPath),
    }),
  );
  return {
    format: 'DTCG Format Module 2025.10',
    schemaVersion: 1,
    sourceHash: hashSource(sourceHash(model)),
    sourceFiles: sourceFiles(),
    appearance: 'dark',
    values: resolvedValues(model, 'dark'),
    reference,
    semantic,
  };
};

export const generateArtifacts = (model) => ({
  'tokens.css': generateCss(model),
  'tokens.ts': generateTokensTs(model),
  'tokens.js': generateTokensJs(model),
  'tokens.d.ts': generateDts(model),
  'manifest.json': `${JSON.stringify(generateManifest(model), null, 2)}\n`,
});

export const buildArtifacts = async ({ outputRoot = generatedRoot } = {}) => {
  const model = await loadTokenModel();
  const errors = [...validateTokenModel(model), ...validateContrast(model)];
  if (errors.length > 0)
    throw new Error(`Token validation failed:\n${errors.map((error) => `- ${error}`).join('\n')}`);
  const artifacts = generateArtifacts(model);
  await mkdir(outputRoot, { recursive: true });
  await Promise.all(
    Object.entries(artifacts).map(([fileName, content]) =>
      writeFile(path.join(outputRoot, fileName), content, 'utf8'),
    ),
  );
  return { files: Object.keys(artifacts), outputRoot };
};

const isCli = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isCli) {
  try {
    const result = await buildArtifacts();
    console.log(`Token artifacts generated: ${result.files.join(', ')}`);
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
