import { access, readFile } from 'node:fs/promises';

const mapUrl = new URL('../../testing/accessibility/coverage-map.json', import.meta.url);
const checklistUrl = new URL(
  '../../testing/accessibility/screen-reader-checklist.md',
  import.meta.url,
);
const reportUrl = new URL(
  '../../testing/accessibility/known-limitations.generated.md',
  import.meta.url,
);
const map = JSON.parse(await readFile(mapUrl, 'utf8'));
const checklist = await readFile(checklistUrl, 'utf8');
const report = await readFile(reportUrl, 'utf8');

const requiredAreas = new Set([
  'keyboard',
  'focus-and-dialogue',
  'semantics-and-relationships',
  'status-and-error-announcement',
  'contrast-and-forced-colors',
  'target-size',
  'motion',
  'resize-reflow',
  'language-and-localization',
]);
const statuses = new Set(map.evidencePolicy.statusValues);

if (map.baseline !== 'WCAG 2.2 AA')
  throw new Error('Accessibility baseline must remain WCAG 2.2 AA.');
if (map.version !== 1 || !Array.isArray(map.areas))
  throw new Error('Invalid accessibility coverage map version.');
if (map.areas.length !== requiredAreas.size)
  throw new Error('Coverage map is missing an accessibility area.');

for (const area of map.areas) {
  if (!requiredAreas.has(area.id))
    throw new Error(`Unexpected or missing coverage area: ${area.id}`);
  if (!statuses.has(area.status)) throw new Error(`Invalid status for ${area.id}: ${area.status}`);
  if (!area.successCriteria.length || !area.evidence.length) {
    throw new Error(`Coverage area must include criteria and evidence: ${area.id}`);
  }
  for (const evidencePath of area.evidence) {
    await access(new URL(`../../${evidencePath}`, import.meta.url));
  }
}

for (const heading of [
  '## Windows: NVDA with Chromium',
  '## macOS: VoiceOver with Safari',
  '## Evidence recording',
]) {
  if (!checklist.includes(heading))
    throw new Error(`Screen reader checklist is missing: ${heading}`);
}
if (!report.includes('Generated by tooling/accessibility/report.mjs')) {
  throw new Error('Generated accessibility report is stale or hand-edited.');
}
for (const area of map.areas) {
  const row = report.split('\n').find((line) => line.startsWith('|') && line.includes(area.id));
  if (!row || !row.trimEnd().endsWith(`| ${area.status} |`)) {
    throw new Error(`Generated accessibility report is missing ${area.id}.`);
  }
}

console.log(`Accessibility coverage check passed (${map.areas.length} areas).`);
