import { readFile, writeFile } from 'node:fs/promises';

const mapPath = new URL('../../testing/accessibility/coverage-map.json', import.meta.url);
const reportPath = new URL(
  '../../testing/accessibility/known-limitations.generated.md',
  import.meta.url,
);
const coverageMap = JSON.parse(await readFile(mapPath, 'utf8'));

const rows = coverageMap.areas.map((area) => {
  const criteria = area.successCriteria.join(', ');
  const evidence = area.evidence.map((path) => `\`${path}\``).join('<br>');
  return `| ${area.id} | ${criteria} | ${evidence} | ${area.status} |`;
});

const report = [
  '<!-- Generated by tooling/accessibility/report.mjs. Do not edit directly. -->',
  '# Accessibility coverage and known limitations',
  '',
  `Baseline: **${coverageMap.baseline}**. Scope: ${coverageMap.scope.join(', ')}.`,
  '',
  'A `partial` or `planned` row is a known limitation for the current infrastructure baseline. It is not evidence that the related Component or Product is non-conformant; the owning Component Contract and manual evidence decide release readiness.',
  '',
  '| Area | Success criteria | Evidence | Status |',
  '| --- | --- | --- | --- |',
  ...rows,
  '',
  'Automated Axe and browser checks are supporting evidence. Stable candidates also require the manual NVDA/Chromium and VoiceOver/Safari checklist and a linked issue or accepted governance decision for unresolved findings.',
  '',
].join('\n');

await writeFile(reportPath, report, 'utf8');
console.log(`Wrote ${reportPath.pathname}`);
