import {
  access,
  mkdir,
  open,
  readdir,
  readFile,
  rm,
  stat,
  unlink,
  writeFile,
} from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const generatorDirectory = path.dirname(fileURLToPath(import.meta.url));
export const repoRoot = path.resolve(generatorDirectory, '../..');
export const docsRoot = path.join(repoRoot, 'apps/docs');
export const contentRoot = path.join(docsRoot, 'content');
export const staticRoot = path.join(docsRoot, 'static');
export const generatedContentRoot = path.join(contentRoot, 'generated');
export const generatedStaticRoot = path.join(staticRoot, 'generated');
export const generatedMarker = '<!-- Generated by tooling/docs-generator. Do not edit. -->';
const generationLockPath = path.join(docsRoot, '.docs-generator.lock');

const componentRoot = path.join(repoRoot, 'specs/components');
const patternRoot = path.join(repoRoot, 'specs/patterns');
const figmaMappingPath = path.join(repoRoot, 'figma/mapping/components.json');
const tokenManifestPath = path.join(repoRoot, 'packages/tokens/generated/manifest.json');

const readJson = async (filePath) => JSON.parse(await readFile(filePath, 'utf8'));

const listJsonFiles = async (directory) => {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const filePath = path.join(directory, entry.name);
    if (entry.isDirectory()) files.push(...(await listJsonFiles(filePath)));
    else if (entry.isFile() && entry.name.endsWith('.json')) files.push(filePath);
  }
  return files.sort();
};

const exists = async (filePath) => {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
};

export const slugify = (value) =>
  value
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/\s+/g, '-')
    .replace(/[^a-zA-Z0-9-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .toLowerCase();

export const displayLabel = (value) =>
  value.replace(/[-_]+/g, ' ').replace(/\b\w/g, (character) => character.toUpperCase());

const posixRelative = (filePath) => path.relative(repoRoot, filePath).split(path.sep).join('/');

const mdText = (value) =>
  String(value ?? '—')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('|', '\\|')
    .replaceAll('\r\n', '<br />')
    .replaceAll('\n', '<br />');

const mdCode = (value) => `\`${String(value ?? '—').replaceAll('`', "'")}\``;

const listValue = (value) => {
  if (Array.isArray(value)) return value.map(mdCode).join(', ');
  if (value && typeof value === 'object') return mdCode(JSON.stringify(value));
  return mdText(value);
};

const storyDetails = async (metadata) => {
  const storyFile = path.join(repoRoot, metadata.source, `${metadata.name}.stories.tsx`);
  if (!(await exists(storyFile))) return { path: null, title: null };
  const source = await readFile(storyFile, 'utf8');
  const title = source.match(/title:\s*['"]([^'"]+)['"]/)?.[1] ?? null;
  return { path: posixRelative(storyFile), title };
};

const componentDetails = async (filePath, figmaComponents) => {
  const metadata = await readJson(filePath);
  const story = await storyDetails(metadata);
  const metadataPath = posixRelative(filePath);
  const specMarkdown = filePath.replace(/\.json$/, '.md');
  const figma = figmaComponents.find(
    (entry) => entry.category === metadata.category && entry.name === metadata.name,
  );
  return {
    ...metadata,
    slug: slugify(metadata.name),
    metadataPath,
    narrativePath: ((await exists(specMarkdown)) && posixRelative(specMarkdown)) || null,
    storyPath: story.path,
    storyTitle: story.title,
    docsPath: `/docs/components/${metadata.category}/${slugify(metadata.name)}`,
    figmaKey: figma?.depoUiKey ?? null,
    figmaComponentSet: figma?.componentSet ?? null,
  };
};

const patternDetails = async (filePath) => {
  const metadata = await readJson(filePath);
  const narrativePath = filePath.replace(/\.json$/, '.md');
  return {
    ...metadata,
    slug: slugify(metadata.id),
    metadataPath: posixRelative(filePath),
    narrativePath: ((await exists(narrativePath)) && posixRelative(narrativePath)) || null,
    docsPath: `/docs/patterns/${slugify(metadata.id)}`,
  };
};

export const collectDocsModel = async () => {
  const figmaMapping = await readJson(figmaMappingPath);
  const tokenManifest = await readJson(tokenManifestPath);
  const componentFiles = await listJsonFiles(componentRoot);
  const patternFiles = await listJsonFiles(patternRoot);
  const components = await Promise.all(
    componentFiles.map((filePath) => componentDetails(filePath, figmaMapping.components ?? [])),
  );
  const patterns = await Promise.all(patternFiles.map(patternDetails));
  const themes = Object.keys(tokenManifest.themes ?? {}).sort();
  const semanticCount = Array.isArray(tokenManifest.semantic)
    ? tokenManifest.semantic.length
    : Object.keys(tokenManifest.semantic ?? {}).length;
  return {
    components: components.sort((left, right) =>
      `${left.category}/${left.name}`.localeCompare(`${right.category}/${right.name}`),
    ),
    patterns: patterns.sort((left, right) => left.id.localeCompare(right.id)),
    tokens: {
      themes,
      referenceCount: Array.isArray(tokenManifest.reference)
        ? tokenManifest.reference.length
        : Object.keys(tokenManifest.reference ?? {}).length,
      semanticCount,
      sourceHash: tokenManifest.sourceHash ?? null,
    },
    figma: {
      mappingPath: 'figma/mapping/components.json',
      componentCount: (figmaMapping.components ?? []).length,
    },
  };
};

const table = (rows) => {
  const lines = ['| Field | Contract |', '| --- | --- |'];
  for (const [key, value] of rows) lines.push(`| ${mdText(key)} | ${listValue(value)} |`);
  return lines.join('\n');
};

export const componentMdx = (component) => {
  const contractRows = [
    ['Purpose', component.purpose],
    ['Anatomy', component.anatomy],
    ['Variants', component.variants],
    ['Sizes', component.sizes],
    ['Tone', component.tones],
    ['States', component.states],
    ['Props', component.props],
    ['Events', component.events],
    ['Keyboard behavior', component.keyboardBehavior],
    ['Focus behavior', component.focusBehavior],
    ['Semantic HTML', component.semanticHtml],
    ['ARIA', component.aria],
    ['Content rules', component.contentRules],
    ['Responsive behavior', component.responsiveBehavior],
    ['Density behavior', component.densityBehavior],
    ['Theme behavior', component.themeBehavior],
    ['Loading behavior', component.loadingBehavior],
    ['Error behavior', component.errorBehavior],
    ['Recovery behavior', component.recoveryBehavior],
    ['Accessibility', component.accessibility],
    ['Tests', component.tests],
  ];
  const sourceRows = [
    ['Metadata', mdCode(component.metadataPath)],
    ['Component source', mdCode(component.source)],
    ['Story', component.storyPath ? mdCode(component.storyPath) : 'Not available yet'],
    [
      'Formal narrative',
      component.narrativePath ? mdCode(component.narrativePath) : 'Not available yet',
    ],
    ['Figma key', component.figmaKey ? mdCode(component.figmaKey) : 'Not mapped'],
    [
      'Figma component set',
      component.figmaComponentSet ? mdCode(component.figmaComponentSet) : 'Not mapped',
    ],
  ];
  return `${generatedMarker}
---
id: generated/components/${component.category}/${component.slug}-api
title: ${component.name}
description: ${String(component.purpose).replaceAll('\n', ' ')}
sidebar_label: ${component.name}
---

# ${component.name}

<span className="dui-doc-status dui-doc-status--${component.lifecycle}">${displayLabel(component.lifecycle)}</span>

This reference is generated from the Component Contract. Editorial guidance belongs in the formal specification and is linked below when available.

## Contract

${table(contractRows)}

## Source and parity

${table(sourceRows)}

## Change policy

Lifecycle is ${mdCode(component.lifecycle)}. API, accessibility, responsive, content, test, and Figma changes must update the metadata and its evidence together. The generated section is read-only; edit the JSON specification, story, or source instead.
`;
};

export const patternMdx = (pattern) => `${generatedMarker}
---
id: generated/patterns/${pattern.slug}
title: ${pattern.name}
description: ${String(pattern.purpose).replaceAll('\n', ' ')}
sidebar_label: ${pattern.name}
---

# ${pattern.name}

<span className="dui-doc-status dui-doc-status--${pattern.lifecycle}">${displayLabel(pattern.lifecycle)}</span>

${pattern.purpose}

## Composition

${table([
  ['Components', pattern.components],
  ['States', pattern.states],
  ['Recovery', pattern.recovery],
  ['Responsive behavior', pattern.responsive],
  ['Accessibility', pattern.accessibility],
])}

## Source

${table([
  ['Metadata', mdCode(pattern.metadataPath)],
  ['Pattern source', pattern.source ? mdCode(pattern.source) : 'Not provided in metadata'],
  ['Formal narrative', pattern.narrativePath ? mdCode(pattern.narrativePath) : 'Not available yet'],
])}

The Pattern composes Components without moving product-specific data fetching, routing, or domain rules into the Core package.
`;

const previewStyles = `
:where(*, *::before, *::after) { box-sizing: border-box; }
:where(html) { color-scheme: dark; }
:where(body) { margin: 0; font-family: system-ui, sans-serif; line-height: 1.5; }
:where(a) { color: inherit; }
.dui-preview-shell { min-block-size: 100vh; padding: 1rem; }
.dui-preview-nav { display: flex; flex-wrap: wrap; gap: 0.75rem; margin-block-end: 2rem; }
.dui-preview-main { margin-inline: auto; max-inline-size: 72rem; }
.dui-preview-grid { display: grid; gap: 1rem; grid-template-columns: repeat(auto-fit, minmax(min(100%, 16rem), 1fr)); }
.dui-preview-card { border: 0.0625rem solid currentColor; border-radius: 0.5rem; padding: 1rem; }
.dui-preview-card p { overflow-wrap: anywhere; }
.dui-preview-search { display: grid; gap: 0.5rem; margin-block: 2rem; max-inline-size: 30rem; }
.dui-preview-search input { font: inherit; inline-size: 100%; padding: 0.75rem; }
@media (prefers-reduced-motion: reduce) { *, *::before, *::after { scroll-behavior: auto !important; transition-duration: 0s !important; } }
`;

const previewHtml = (navigation, model) => {
  const nav = navigation.map((item) => `<a href="${item.path}">${mdText(item.label)}</a>`).join('');
  const cards = navigation
    .map(
      (item) =>
        `<article class="dui-preview-card"><h2><a href="${item.path}">${mdText(item.label)}</a></h2><p>${mdText(item.description)}</p></article>`,
    )
    .join('');
  return `<!doctype html>
<html lang="en" data-theme="dark" data-density="comfortable" dir="ltr">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Depo UI documentation preview</title>
    <style>${previewStyles}</style>
  </head>
  <body>
    <a href="#main-content">Skip to content</a>
    <div class="dui-preview-shell">
      <nav aria-label="Documentation sections" class="dui-preview-nav">${nav}</nav>
      <main class="dui-preview-main" id="main-content">
        <p>Depo UI Design System</p>
        <h1>Build clear, resilient Web applications.</h1>
        <p>Generated documentation preview with ${model.components.length} Components and ${model.patterns.length} Patterns.</p>
        <div class="dui-preview-search" role="search">
          <label for="preview-search">Search documentation</label>
          <input id="preview-search" type="search" placeholder="Search components and patterns" />
        </div>
        <section aria-labelledby="preview-sections"><h2 id="preview-sections">Explore Depo UI</h2><div class="dui-preview-grid">${cards}</div></section>
        <section aria-labelledby="preview-adaptive"><h2 id="preview-adaptive">Adaptive example</h2><p lang="ja">狭いコンテナでも長い日本語の説明文が読みやすく折り返されます。</p><button type="button">Continue</button></section>
      </main>
    </div>
  </body>
</html>
`;
};

export const docsNavigation = async () => readJson(path.join(docsRoot, 'navigation.json'));

export const generateMdx = async (model) => {
  await rm(generatedContentRoot, { recursive: true, force: true });
  await mkdir(generatedContentRoot, { recursive: true });
  for (const component of model.components) {
    const directory = path.join(generatedContentRoot, 'components', component.category);
    await mkdir(directory, { recursive: true });
    await writeFile(
      path.join(directory, `${component.slug}-api.mdx`),
      componentMdx(component),
      'utf8',
    );
  }
  for (const pattern of model.patterns) {
    const directory = path.join(generatedContentRoot, 'patterns');
    await mkdir(directory, { recursive: true });
    await writeFile(path.join(directory, `${pattern.slug}.mdx`), patternMdx(pattern), 'utf8');
  }
};

const searchEntries = (navigation, model) => [
  ...navigation.map((item) => ({
    title: item.label,
    description: item.description,
    path: item.path,
    kind: 'section',
  })),
  ...model.components.map((component) => ({
    title: component.name,
    description: component.purpose,
    path: component.docsPath,
    kind: 'component',
  })),
  ...model.patterns.map((pattern) => ({
    title: pattern.name,
    description: pattern.purpose,
    path: pattern.docsPath,
    kind: 'pattern',
  })),
];

export const writeManifest = async (navigation, model) => {
  await rm(generatedStaticRoot, { recursive: true, force: true });
  await mkdir(generatedStaticRoot, { recursive: true });
  const manifest = {
    schemaVersion: 1,
    generatedBy: 'tooling/docs-generator',
    marker: generatedMarker,
    navigation,
    counts: {
      components: model.components.length,
      patterns: model.patterns.length,
      searchEntries: searchEntries(navigation, model).length,
    },
    tokens: model.tokens,
    figma: model.figma,
    components: model.components.map((component) => ({
      name: component.name,
      category: component.category,
      lifecycle: component.lifecycle,
      metadataPath: component.metadataPath,
      sourcePath: component.source,
      storyPath: component.storyPath,
      docsPath: component.docsPath,
      figmaKey: component.figmaKey,
    })),
    patterns: model.patterns.map((pattern) => ({
      id: pattern.id,
      name: pattern.name,
      metadataPath: pattern.metadataPath,
      sourcePath: pattern.source ?? null,
      docsPath: pattern.docsPath,
    })),
  };
  await writeFile(
    path.join(generatedStaticRoot, 'docs-manifest.json'),
    `${JSON.stringify(manifest, null, 2)}\n`,
    'utf8',
  );
  await writeFile(
    path.join(generatedStaticRoot, 'search.json'),
    `${JSON.stringify(searchEntries(navigation, model), null, 2)}\n`,
    'utf8',
  );
  await writeFile(
    path.join(generatedStaticRoot, 'docs-preview.html'),
    previewHtml(navigation, model),
    'utf8',
  );
};

const delay = (milliseconds) =>
  new Promise((resolve) => globalThis.setTimeout(resolve, milliseconds));

const acquireGenerationLock = async () => {
  for (let attempt = 0; attempt < 800; attempt += 1) {
    try {
      return await open(generationLockPath, 'wx');
    } catch (error) {
      if (error.code !== 'EEXIST') throw error;
      try {
        const lockAge = Date.now() - (await stat(generationLockPath)).mtimeMs;
        if (lockAge > 10_000) await unlink(generationLockPath);
      } catch (statError) {
        if (statError.code !== 'ENOENT') throw statError;
      }
      await delay(25);
    }
  }
  throw new Error(`Timed out waiting for docs generation lock: ${generationLockPath}`);
};

export const generateDocs = async () => {
  const lock = await acquireGenerationLock();
  try {
    const model = await collectDocsModel();
    const navigation = await docsNavigation();
    await generateMdx(model);
    await writeManifest(navigation, model);
    return { model, navigation };
  } finally {
    await lock.close();
    await unlink(generationLockPath).catch((error) => {
      if (error.code !== 'ENOENT') throw error;
    });
  }
};
