import type { PatternDefinition } from './types.js';

export const patternDefinitions: readonly PatternDefinition[] = [
  {
    id: 'form-submission',
    title: 'Form submission',
    userGoal: 'Submit valid information and recover without losing entered values.',
    components: ['Field', 'Button', 'InlineMessage'],
    states: ['idle', 'editing', 'submitting', 'success', 'error'],
    recovery: ['field correction', 'server retry', 'preserve input'],
    responsive: 'Use a single column on narrow containers and keep submit actions visible.',
    accessibility: ['label/error association', 'submit keyboard', 'busy announcement'],
    lifecycle: 'trial',
  },
  {
    id: 'search-and-filter',
    title: 'Search and filter',
    userGoal: 'Find relevant records while understanding the active query and filters.',
    components: ['SearchField', 'Combobox', 'Select', 'Tag', 'List', 'Table'],
    states: ['idle', 'loading', 'results', 'empty', 'error'],
    recovery: ['retry', 'clear filter', 'preserve query'],
    responsive:
      'Wrap the filter bar and move secondary filters into a drawer on narrow containers.',
    accessibility: [
      'result count live region',
      'keyboard filter removal',
      'do not conflate empty and error',
    ],
    lifecycle: 'trial',
  },
  {
    id: 'list-detail',
    title: 'List detail',
    userGoal: 'Select a record and move between its summary and detail without losing context.',
    components: ['List', 'Card', 'Drawer', 'Dialog', 'Pagination'],
    states: ['idle', 'loading', 'selected', 'error'],
    recovery: ['retry detail', 'back to list', 'preserve selection'],
    responsive:
      'Use list-to-detail navigation on narrow containers and split panes on wide containers.',
    accessibility: ['selected item state', 'heading hierarchy', 'focus return'],
    lifecycle: 'trial',
  },
  {
    id: 'create',
    title: 'Create',
    userGoal: 'Create a new resource with clear validation and destination after success.',
    components: ['Field', 'Dialog', 'Drawer', 'Button', 'InlineMessage'],
    states: ['idle', 'editing', 'submitting', 'created', 'error', 'cancel'],
    recovery: ['correct validation', 'retry', 'cancel without data loss'],
    responsive:
      'Prefer a full-screen form or route on narrow containers and a dialog on wide containers.',
    accessibility: ['focus trap', 'unsaved changes', 'error association'],
    lifecycle: 'trial',
  },
  {
    id: 'edit',
    title: 'Edit',
    userGoal: 'Change an existing resource and understand whether changes are saved.',
    components: ['Field', 'Button', 'Banner'],
    states: ['view', 'editing', 'dirty', 'saving', 'saved', 'error'],
    recovery: ['resolve conflict', 'reload or merge', 'preserve draft'],
    responsive: 'Reflow the action bar while retaining the primary save action.',
    accessibility: ['dirty state announcement', 'keyboard save', 'long text preservation'],
    lifecycle: 'trial',
  },
  {
    id: 'delete',
    title: 'Delete',
    userGoal: 'Remove a resource only after understanding its impact.',
    components: ['Button', 'IconButton', 'Dialog', 'Toast'],
    states: ['idle', 'confirm', 'deleting', 'deleted', 'error'],
    recovery: ['retry', 'undo or restore', 'preserve affected count'],
    responsive: 'Keep destructive and safe actions in a predictable order at every width.',
    accessibility: ['explicit confirmation', 'safe default focus', 'non-color warning'],
    lifecycle: 'trial',
  },
  {
    id: 'destructive-action',
    title: 'Destructive action',
    userGoal: 'Understand an irreversible action before confirming it.',
    components: ['Dialog', 'Button', 'InlineMessage'],
    states: ['idle', 'confirm', 'processing', 'complete'],
    recovery: ['cancel', 'alternative action', 'support path'],
    responsive: 'Maintain readable impact text and action order on narrow screens.',
    accessibility: ['dialog semantics', 'safe focus', 'text independent of color'],
    lifecycle: 'trial',
  },
  {
    id: 'async-action',
    title: 'Async action',
    userGoal: 'Understand progress and outcome for a background or remote action.',
    components: ['Button', 'ProgressBar', 'InlineMessage'],
    states: ['idle', 'pending', 'success', 'warning', 'error'],
    recovery: ['cancel', 'retry', 'partial success'],
    responsive: 'Keep progress and status discoverable without relying on animation.',
    accessibility: ['aria-busy', 'live result', 'reduced motion'],
    lifecycle: 'trial',
  },
  {
    id: 'error-recovery',
    title: 'Error recovery',
    userGoal: 'Understand a problem and resume work with the smallest safe next action.',
    components: ['ErrorState', 'InlineMessage', 'Button', 'Link'],
    states: ['error', 'retry', 'loading', 'recovered'],
    recovery: ['explain problem', 'give correction', 'retry without reset'],
    responsive: 'Separate page, section, and field errors without hiding the affected context.',
    accessibility: ['heading', 'focus policy', 'alert/status distinction'],
    lifecycle: 'trial',
  },
  {
    id: 'empty-state',
    title: 'Empty state',
    userGoal:
      'Tell whether data is new, filtered out, unavailable, or failed and provide a next action.',
    components: ['EmptyState', 'Button', 'Link'],
    states: ['loading', 'empty', 'filtered-empty', 'error'],
    recovery: ['create', 'clear filters', 'learn more'],
    responsive: 'Wrap actions and preserve readable explanation on narrow screens.',
    accessibility: ['heading', 'action label', 'decorative media policy'],
    lifecycle: 'trial',
  },
  {
    id: 'loading',
    title: 'Loading',
    userGoal: 'Understand what is loading while existing content remains stable where possible.',
    components: ['Skeleton', 'Spinner', 'ProgressBar', 'InlineMessage'],
    states: ['idle', 'loading', 'content', 'empty', 'error'],
    recovery: ['timeout', 'retry', 'preserve content'],
    responsive: 'Reserve layout space and avoid hiding required content behind a skeleton.',
    accessibility: ['status', 'aria-busy', 'reduced motion'],
    lifecycle: 'trial',
  },
  {
    id: 'data-management',
    title: 'Data management',
    userGoal: 'Browse, filter, sort, paginate, and inspect records with a stable data context.',
    components: ['Table', 'DataGrid', 'SearchField', 'Select', 'Pagination', 'Drawer'],
    states: ['idle', 'fetching', 'ready', 'empty', 'error'],
    recovery: ['retry', 'preserve query', 'detail alternative'],
    responsive: 'Prioritize columns and provide a detail alternative for narrow containers.',
    accessibility: ['table/grid distinction', 'keyboard grid model', 'selection announcement'],
    lifecycle: 'trial',
  },
  {
    id: 'bulk-action',
    title: 'Bulk action',
    userGoal: 'Apply an action to a known set of selected records and understand partial outcomes.',
    components: ['Checkbox', 'DataGrid', 'Button', 'Dialog', 'Toast'],
    states: [
      'none-selected',
      'some-selected',
      'all-selected',
      'processing',
      'partial',
      'success',
      'error',
    ],
    recovery: ['retry failed items', 'undo', 'preserve selection'],
    responsive: 'Announce scope and keep the selection action bar usable on narrow screens.',
    accessibility: ['selection summary', 'scope label', 'progress/result announcement'],
    lifecycle: 'trial',
  },
  {
    id: 'responsive-navigation',
    title: 'Responsive navigation',
    userGoal: 'Reach application destinations as navigation changes with available space.',
    components: ['TopNav', 'SideNav', 'Drawer', 'Menu', 'SkipLink'],
    states: ['permanent', 'persistent', 'temporary'],
    recovery: ['keep main content', 'focus return', 'escape close'],
    responsive: 'Use container width and input method to transform navigation between modes.',
    accessibility: ['landmarks', 'toggle name', 'focus return', 'skip link'],
    lifecycle: 'trial',
  },
  {
    id: 'permission-state',
    title: 'Permission state',
    userGoal:
      'Understand whether access is checking, limited, denied, or available and what to do next.',
    components: ['Banner', 'InlineMessage', 'Button', 'Link'],
    states: ['checking', 'allowed', 'limited', 'denied'],
    recovery: ['request access', 'switch account', 'learn more'],
    responsive: 'Keep the reason and next action visible at every width.',
    accessibility: ['explain disabled actions', 'status', 'privacy-safe text'],
    lifecycle: 'trial',
  },
  {
    id: 'unavailable-state',
    title: 'Unavailable state',
    userGoal: 'Distinguish deleted, offline, unsupported, and temporarily unavailable resources.',
    components: ['ErrorState', 'InlineMessage', 'Button', 'Link'],
    states: ['available', 'unavailable', 'retry', 'alternate'],
    recovery: ['retry', 'alternate route', 'offline action'],
    responsive: 'Keep status heading and recovery action readable in constrained containers.',
    accessibility: ['status heading', 'named action', 'offline fallback'],
    lifecycle: 'trial',
  },
  {
    id: 'undo',
    title: 'Undo',
    userGoal: 'Reverse a recent reversible action before its recovery window expires.',
    components: ['Toast', 'Button'],
    states: ['completed', 'undo-window', 'restored', 'expired'],
    recovery: ['undo failure resync', 'history alternative', 'do not lose source'],
    responsive: 'Make the action reachable without blocking the page or moving focus unexpectedly.',
    accessibility: ['live region', 'timeout awareness', 'alternate recovery'],
    lifecycle: 'trial',
  },
  {
    id: 'authentication',
    title: 'Authentication',
    userGoal: 'Sign in, verify, recover, and re-authenticate without ambiguous errors.',
    components: ['Field', 'Button', 'InlineMessage', 'Link'],
    states: ['signed-out', 'authenticating', 'authenticated', 'error', 'expired'],
    recovery: ['field correction', 'password manager', 'recovery flow'],
    responsive: 'Use a readable single-column form and preserve error context on narrow screens.',
    accessibility: ['accessible authentication', 'autocomplete', 'one fact per field'],
    lifecycle: 'trial',
  },
  {
    id: 'command-palette',
    title: 'Command palette',
    userGoal: 'Find and run a command from the keyboard while preserving context.',
    components: ['CommandPalette', 'Combobox', 'Kbd', 'Dialog'],
    states: ['closed', 'open', 'query', 'result', 'empty', 'executing', 'error'],
    recovery: ['keep query', 'retry command', 'permission explanation'],
    responsive:
      'Use a full-width modal surface on narrow screens and a constrained panel on wide screens.',
    accessibility: ['Ctrl/Cmd+K is supplemental', 'focus trap', 'result announcement', 'Escape'],
    lifecycle: 'trial',
  },
];

export function getPatternDefinition(id: string) {
  return patternDefinitions.find((pattern) => pattern.id === id);
}
